### PR TITLE
fix(worker): fix pause/resume functionality

### LINKED ISSUE #650: Handle `is_shutting_down()` and `pause` correctly
### Discussed in https://github.com/orgs/apalis-dev/discussions/647

<div type='discussions-op-text'>

<sup>Originally posted by **Himmelschmidt** December 18, 2025</sup>
I'm using `pause()` to temporarily halt a worker when authentication expires, intending to `resume()` once the user re-authenticates. However, I discovered that paused workers sometimes cannot be resumed:

1. `is_shutting_down()` returns `true` for paused workers (since it checks `!self.is_running()`)
2. If in-flight tasks exist: `resume()` fails with `ShuttingDown` error (line 200 check)
3. If no in-flight tasks: the `WorkerContext` Future resolves (`is_shutting_down() && task_count == 0`), and the worker exits entirely

```rust
// Current implementation - treats Paused as "shutting down"
pub fn is_shutting_down(&self) -> bool {
    self.shutdown
        .as_ref()
        .map(|s| !self.is_running() || s.is_shutting_down())
        .unwrap_or(!self.is_running())  // <- Paused workers hit this
}
```

Is this intentional? If `pause()` is meant for very brief operational pauses only, what's the recommended pattern for temporarily halting a worker until an external condition is met?

I've worked around this in my fork by checking for `Stopped` state explicitly rather than `!is_running()`, but wanted to confirm before proposing a PR.
</div>

### PR DESCRIPTION
**Pull request by Himmelschmidt**
## Summary

Fixes #650 

**Root cause:** `is_shutting_down()` returned true for paused workers (checked `!self.is_running()`), causing:
- `resume()` to fail with `ShuttingDown` error when in-flight tasks existed
- Workers with no in-flight tasks to exit entirely

**Fix:** 
- `is_shutting_down()` now only returns true when state is `Stopped` or shutdown signal is triggered
- `ReadinessService::poll_ready()` now explicitly checks `is_paused()` to block new job processing

Also suppresses spurious error log when dropping `WorkerContext` with no pending tasks.

### CODE REVIEW

File: apalis-core/src/worker/context.rs [hunk 1]
```diff
@@ -376,3 +382,116 @@ impl Drop for WorkerContext {
         }
     }
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (geofmureithi) [inline apalis-core/src/worker/context.rs]: TBH these tests look like overkill. They also dont actually test a worker.
I would recommend writing test(s) and using `run_with_ctx`.
```rs
pub async fn run_with_ctx(self, ctx: &mut WorkerContext) -> Result<(), WorkerError> {
```
You could run the worker separately and then control it with the context ref.

**Comment by geofmureithi** [comment]
@Himmelschmidt Let me know if you need some help

**Comment by Himmelschmidt** [comment]
I should be able to do it, seems minor enough, I just have to find the time to actually do it, might take a day or two

**Comment by geofmureithi** [comment]
FYI: Sorry for the strict approach on this one, it affects core parts of the project.
